-- ================================================================
-- SCRIPT  : MI4014_EXT_TABLE.sql
-- SYSTEM  : Credit Risk Behaviour Scoring - Neptune Data Load
-- PURPOSE : Oracle External Table DDL for MI4014 daily transaction
--           extract. Reads XML file generated by mainframe CRXMLGEN
--           and placed in NEPTUNE_FILES_LOAD directory.
--
-- SCHEMA  : BDD_NEPTUNE_DICC
-- TABLE   : MI4014_TRANSACCIONES_DIARIAS
-- DIR OBJ : NEPTUNE_FILES_LOAD
-- XML FILE: MI4014_Transaction_Extract_TSB_NAM65_YYYYMMDD.xml
--
-- DATA FLOW:
--   DB2 CRISK.CUST_ACCOUNT_MASTER
--     → COBOL CRDB2EXT → CUST.BHSCORE.EXTRACT
--   DB2 CRISK.DAILY_TRANSACTIONS
--     → COBOL CRTXNEXT → TRANS.BHSCORE.EXTRACT
--   DFSORT MERGE (CRJBHSCR STEP030)
--     → MERGED.BHSCORE.EXTRACT
--   COBOL CRXMLGEN → MI4014_Transaction_Extract_TSB_NAM65_DATE.xml
--   Oracle External Table (this DDL) reads XML
-- ================================================================

CREATE TABLE "BDD_NEPTUNE_DICC"."MI4014_TRANSACCIONES_DIARIAS"
   (
    "MAIN_ACCOUNT_NUMBER"  VARCHAR2(4000 BYTE),
    "SUB_ACCOUNT_NUMBER"   VARCHAR2(4000 BYTE),
    "COMPANY"              VARCHAR2(4000 BYTE),
    "TRANSACTION_CODE"     VARCHAR2(4000 BYTE),
    "TRANSACTION_AMOUNT"   VARCHAR2(4000 BYTE),
    "TRANSACTION_GROUP"    VARCHAR2(4000 BYTE),
    "POSTED_DATE"          VARCHAR2(4000 BYTE),
    "EFFECTIVE_DATE"       VARCHAR2(4000 BYTE),
    "UNSECURED"            VARCHAR2(4000 BYTE),
    "NEW_MAIN_ACC_NUM"     VARCHAR2(4000 BYTE),
    "NEW_LOAN_ACC_NUM"     VARCHAR2(4000 BYTE)
   )
   ORGANIZATION EXTERNAL
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "NEPTUNE_FILES_LOAD"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY '</Item>'
        FIELDS (
           delim CHAR(2000) TERMINATED BY '<Item>',
           MAIN_ACCOUNT_NUMBER  CHAR(300)
               ENCLOSED BY '<external_account_number>'
               AND '</external_account_number>',
           SUB_ACCOUNT_NUMBER   CHAR(300)
               ENCLOSED BY '<sub_no>'
               AND '</sub_no>',
           COMPANY              CHAR(300)
               ENCLOSED BY '<book_id>'
               AND '</book_id>',
           TRANSACTION_CODE     CHAR(300)
               ENCLOSED BY '<transaction_code>'
               AND '</transaction_code>',
           TRANSACTION_AMOUNT   CHAR(300)
               ENCLOSED BY '<transaction_amt>'
               AND '</transaction_amt>',
           TRANSACTION_GROUP    CHAR(300)
               ENCLOSED BY '<tran_category>'
               AND '</tran_category>',
           POSTED_DATE          CHAR(300)
               ENCLOSED BY '<posted_date>'
               AND '</posted_date>',
           EFFECTIVE_DATE       CHAR(300)
               ENCLOSED BY '<effective_date>'
               AND '</effective_date>',
           UNSECURED            CHAR(300)
               ENCLOSED BY '<unsec_ind>'
               AND '</unsec_ind>',
           NEW_MAIN_ACC_NUM     CHAR(300)
               ENCLOSED BY '<New_Main_Account_Number>'
               AND '</New_Main_Account_Number>',
           NEW_LOAN_ACC_NUM     CHAR(300)
               ENCLOSED BY '<New_Loan_Account_Number>'
               AND '</New_Loan_Account_Number>'
        )
      )
      LOCATION
       ( 'MI4014_Transaction_Extract_TSB_NAM65_20260514.xml'
       )
    )
   REJECT LIMIT UNLIMITED;
